### ISSUE TITLE
Extract an interface for a spinner

### ISSUE THREAD

**Issue by seregazhuk** [alecrabbit/php-cli-snake#1]
In my PHP-Watcher [here](https://github.com/seregazhuk/php-watcher/issues/39) I want to use a "disabled" spinner. I want it just to print nothing. I don't want to use `disable()` functionality, because it forces the consumers of the spinner to know these details: that with some conditionals the spinner should be disabled. It also has added a lot of conditionals in your code, where you have all these `if ($this->enabled)`. Actually, you don't have a method to enable the spinner back 😄 

So, my idea is the following. You can extract an interface `Spinner`. In my package I'm going to have two implementations: your snake spinner and my own let's call it `VoidSpinner`. `VoidSpinner` simply does nothing. It has just `return` statements everywhere. When I don't want the spinner to output to the console I can swith to my void implementation. 

What do you think about it? 🤔

**Comment by alecrabbit** [comment]
Well, it's not a bad idea. I'll think about it. 
Addition of `disable()` was a quick hack attempt 😄 and `enable()` method is absent because it's a "Lightweight cli spinner" 😄 
I mean all this noise is to find a good API solution through talks.

**Comment by seregazhuk** [comment]
Yes, I understand that it was a hack 😄  👍  I suggest to remove this method at all and extract an interface for spinner.

**Comment by alecrabbit** [comment]
Done!
Try it out and let me know how it goes.

**Comment by seregazhuk** [comment]
Thank you! It works great! 🔥 💪
