### ISSUE TITLE
Enable spinner to be placed in console output.

### ISSUE THREAD

**Issue by grasmash** [alecrabbit/php-cli-snake#2]
**Is your feature request related to a problem? Please describe.**
I'm using Symfony console to display output. I'd like to be able to place the spinner at the beginning of a line. E.g.,:
```
$this->section->writeln($spinner . ' Waiting for DNS to propagate');
```

Right now, it seems I can only place the spinner at the very end of my output.

**Comment by alecrabbit** [comment]
this package is as simple as possible
take a look at [php-console-spinner](https://github.com/alecrabbit/php-console-spinner)
