### ISSUE TITLE
Add support for status messages

### ISSUE THREAD

**Issue by aeno** [alecrabbit/php-cli-snake#3]
**Is your feature request related to a problem? Please describe.**
For long running tasks, the spinner is missing a status (or progress) message that can help visualizing that the processing is still running.

**Describe the solution you'd like**
I'd like to show an optional line of text next to the spinner animation. This status message can be set via a setter method on the spinner class. If a message is set, it will be added to the spinner output.

**Describe alternatives you've considered**
I considered using https://github.com/alecrabbit/php-console-spinner for this, but didn't want to have all its additional features and complexity.

**Additional context**
I created a fork that suggests an implementation of this feature and will create a PR.

**Comment by alecrabbit** [comment]
this feature to be reliable requires few dependencies and it will brake package lightness.
this package was created  be to as light as possible and it's called `snake`(not `spinner`) for this reason


I am planning to improve https://github.com/alecrabbit/php-console-spinner eventually, you can contribute there.
